package com.example.miusapp.Model

class Student internal constructor(
    val id: String = "",
    val name: String = "",
    val age: Int = 0,
    val percentComplete: Int = 0,
    val theorTrain1First: Int = 0,
    val theorTrain1Second: Int = 0,
    val theorTrain2First: Int = 0,
    val theorTrain2Second: Int = 0,
    val practicTrain1First: Int = 0,
    val practicTrain1Second: Int = 0,
    val practicTrain2First: Int = 0,
    val practicTrain2Second: Int = 0,
    val practicTrain3First: Int = 0,
    val practicTrain3Second: Int = 0,
    val generalTrain1First: Int = 0,
    val generalTrain1Second: Int = 0,
    val generalTrain2First: Int = 0,
    val generalTrain2Second: Int = 0,
    val generalTrain3First: Int = 0,
    val generalTrain3Second: Int = 0,
    val generalTrain4First: Int = 0,
    val generalTrain4Second: Int = 0,
    val generalTrain5First: Int = 0,
    val generalTrain5Second: Int = 0,
    val generalTrain6First: Int = 0,
    val generalTrain6Second: Int = 0,
    val generalTrain7First: Int = 0,
    val generalTrain7Second: Int = 0,
    val generalTrain8First: Int = 0,
    val generalTrain8Second: Int = 0,
    val generalTrain9First: Int = 0,
    val generalTrain9Second: Int = 0,
    val generalTrain10First: Int = 0,
    val generalTrain10Second: Int = 0,
    val generalTrain11First: Int = 0,
    val generalTrain11Second: Int = 0,
)